### ISSUE TITLE
Configuración y despliegue de la aplicación en la nube

### ISSUE THREAD

**Issue by diegosanchezp** [diegosanchezp/tesis#18]
- [x] Configuración de certbox con docker nginx ( HTTPS )
- [x] #20
- [x] #24
- [x] #25
  - [x] #39 
- [x] #31
- ❌ Configurar storages de django con S3

  - Crear policy para que:
    - [x] Los archivos con el prefix `static/` y `public_media` sean accesbles por el público.
    - [x] Los archivos con el prefix `private_media` sean privados.
  - ❌ #22
  - ❌ Configurar Django Storages, para que cuando se ejecute el collectstatic, se suban los archivos con los prefixes correctos.
    - Django storages resulto no ser factible para archivos privados. 
    - Se configuró para archivos estáticos, pero hacer esto implica hacer un job en github actions que compile los assets, ya se hace actualmente cuando la imagen de docker se construye.
