### ISSUE TITLE
Contenido Privado en el CMS de Wagtail

### ISSUE THREAD

**Issue by diegosanchezp** [diegosanchezp/tesis#23]
La mayoría del contenido de la red social de Egresados será solo de consumo para aquellos usuarios que estén identificados.

Por ahora solo se tiene un tipo de contenido que es público: la página Home.

Se necesitan añadir estas features al CMS de Wagtail, cuando se crea una nueva instancia de un tipo de contenido.

Cierto tipo de contenido se debería de poder definir como público

Por defecto, el contenido nuevo a crear debe de ser privado.

## User story
Como usuario administrador, cuando este editando la pagina del homepage y añada un nuevo factor promocional, quiero que la imagen sea marcada automáticamente como publica.

Como otro tipo de usuario que publica contenido, cuando este editando un tipo de contenido, quiero que la las imágenes y otro tipo de archivos se marquen automáticamente como privados.
 
## Posibles estrategias de implementación
- [x] Crear clase, que herede de `wagtail.images.models.AbstractImage`, llamada `WagtailPublicImage`, ver https://docs.wagtail.org/en/stable/advanced_topics/images/custom_image_model.html
- [x] Crear nueva instancia de file storage, `fs = FileSystemStorage(location="/public_media/photos")`, ver https://docs.djangoproject.com/en/4.2/topics/files/#the-built-in-filesystem-storage-class
- [x] Setear atributo file = `WagtailImageField(..., storage=fs`) en `PublicImage`
- [x] Cambiar todas las Foreing Keys que referencia a imagenes con el nuevo modelo `WagtailPublicImage`.
- [ ] setear setting MEDIA a como esta en el de private media.
  - [x] Actualizar urls.py, invertir MEDIA pasa ahora a ser las imagenes privadas
  - [x] PUBLIC_MEDIA es ahora `/media/` 
  - [ ] Actualizar config de nginx.
  - [ ] Actualizar fixture del home.
  - [X] Añadir widget `wagtail.images.widgets.AdminImageChooser` a Field panels ya que se pierde el original. ver https://groups.google.com/g/wagtail/c/6hgCRrJ79WA

Pruebas, 
  - [ ] Imagenes al editar pagina del home se guardan en carpeta media.
  - [ ] Si no estoy logueado, debería de poder ver las imagenes del home.

ver metodo `wagtail.images.models.AbstractImage.get_upload_to` para setear el upload_to
Crear storage nuevo para private files,  que herede de file storage con atributo _location = settings.PrivateMediaFiles

https://docs.wagtail.org/en/stable/advanced_topics/privacy.html

# Problemas encontrados
Utilizar el widget `wagtail.images.widgets.AdminImageChooser`, no guarda los archivos en la carpeta publica ya que hace una llamada al endpoint con ajax

https://github.com/wagtail/wagtail/pull/3644

**Comment by diegosanchezp** [comment]
Cerrando el issue no es posible tener media privada en wagtail, ver

https://github.com/wagtail/wagtail/issues/3880
