### ISSUE TITLE
Conectar formulario de selección de carreras con backend

### ISSUE THREAD

**Issue by diegosanchezp** [diegosanchezp/tesis#57]
Dado que se implementaron los modelos de datos para la página de registro, en el issue #52 , para el formulario de selección de carreras universitarias se requiere que la lista de carreras venga de la base de datos

Para esto se utilzará alpinejs + htmx.

# Tasks
- Instalar e integrar `htmx` con django
  - [x] [django-htmx](https://django-htmx.readthedocs.io/en/latest/) 
  - [x] Evaluar [django-render-block](https://github.com/clokep/django-render-block), ejemplos de uso:
    - [template-fragments-with-django-and-htmx](https://bugbytes.io/posts/template-fragments-with-django-and-htmx/)
    - [django-htmx-patterns](https://github.com/spookylukey/django-htmx-patterns) 
- [x] Integrar htmx con `alpinejs` utilizando plugin [alpine-morph](https://htmx.org/extensions/alpine-morph/). Esto se requiere ya que `alpinejs`, es la dependencia de js que gestiona el localstorage de estas páginas.

- [x] Utilizar patrón de htmx [Active Search](https://htmx.org/examples/active-search/)
  - [x] `select_carrera.html` Definir el `hx-target="#search-results"` a reemplazar
  - [x] `views.py` utilizar django-render-block para que solo el formulario se rederice cuando se esta haciendo un POST request a la view

- [ ] Formulario para el input de búsqueda ?
